{
  Object value;
  try {
    value=invoke(this,"fail","hello");
  }
 catch (  AssertionFailedError e) {
  }
}
