{
  try {
    throw new InvokerException("message",new NullPointerException());
  }
 catch (  InvokerException e) {
    assertEquals("message",e.getMessage());
    assertTrue(e.getCause() instanceof NullPointerException);
  }
}
