{
  try {
    blowup(n);
  }
 catch (  Lo_Exception e) {
    Lo++;
  }
}
