{
  try {
    final Range range=createRange(1,5);
    range.remove(0);
    fail("expected exception not thrown");
  }
 catch (  UnsupportedOperationException e) {
    assertTrue("expected exception thrown",true);
  }
}
