{
  try {
    range.remove(AT);
    fail("removed value from empty range");
  }
 catch (  UnsupportedOperationException e) {
    assertTrue("expected exception thrown",true);
  }
}
