{
  super("Exception thrown by call to closure: " + closure + " reaason: "+ cause,cause);
  this.closure=closure;
}
