{
  try {
    invoke(null,"mockCallWithNoParams",null);
    fail("Should have thrown an exception");
  }
 catch (  NullPointerException e) {
  }
}
